### ISSUE TITLE
Download dataset not working

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#107]
Button to download dataset is not working.

**Comment by leichenxu** [comment]
![image](https://user-images.githubusercontent.com/46742711/85002504-410e1580-b155-11ea-88af-a297e8e0a492.png)
its working @jmcolmenar

**Comment by jmcolmenar** [comment]
Still if I click the button, no file is downloaded.

**Comment by leichenxu** [comment]
> Still if I click the button, no file is downloaded.

can you put a capture of console?

**Comment by jmcolmenar** [comment]
![Captura de pantalla 2020-06-19 a las 9 59 37](https://user-images.githubusercontent.com/4963260/85110727-9e689c00-b213-11ea-8a91-319969b2da3d.png)

**Comment by leichenxu** [comment]
change the site of function for locate it, should be solve the problem @jmcolmenar , check it

**Comment by jmcolmenar** [comment]
Only the first page of the dataset is downloaded, please correct it.

**Comment by leichenxu** [comment]
fixed
