### ISSUE TITLE
Revise number of run

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#116]
When opening the plot of a run, the number of run is missing. Should be added to title.

Besides, in the stats window, the number of run is incorrect when clicking on a finished run whereas other runs are still pending.

**Comment by leichenxu** [comment]
the second problem should be fixed after the form of get run, i can't recreate the problem, @jmcolmenar check it

**Comment by jmcolmenar** [comment]
Seems to work for new experiments. Previous ones are somehow corrupted.
