### ISSUE TITLE
add stats for all runs

### ISSUE THREAD

**Issue by leichenxu** [GRAFO-URJC/WebGE#121]

**Comment by leichenxu** [comment]
in #120  have a comment that stats is not working in list experiment, but i can't recreate the problem
![image](https://user-images.githubusercontent.com/46742711/85198743-6896e680-b2eb-11ea-944e-ac4712384905.png)
@jmcolmenar

**Comment by jmcolmenar** [comment]
Don't see anything. Using Firefox and no error in console.
<img width="1279" alt="Captura de pantalla 2020-06-21 a las 19 35 53" src="https://user-images.githubusercontent.com/4963260/85231344-8f8e0f00-b3f6-11ea-9677-2ca1db8e17a4.png">

**Comment by leichenxu** [comment]
@jmcolmenar  fixed problem
