### ISSUE TITLE
Execution errors control

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#131]
If dataset is wrong (no comment on first line, for instance) or the grammar generates incorrect expressions, no clue is given to the user. Some capture of exceptions should be done and sent to the execution log.

Now it is not possible even to stop execution.

**Comment by leichenxu** [comment]
dataset wrong message
![image](https://user-images.githubusercontent.com/46742711/85851488-12c0b380-b7af-11ea-841b-d5bed62d2efa.png)

**Comment by leichenxu** [comment]
![image](https://user-images.githubusercontent.com/46742711/85857794-cda27e80-b7ba-11ea-8e9d-b976f72b9c56.png)
incorrect grammar message

**Comment by leichenxu** [comment]
status to failed fixed

**Comment by leichenxu** [comment]
@jmcolmenar check it please
