### ISSUE TITLE
Wider field for grammar

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#140]
When saving an experiment with a long grammar (~500 char), an error is launched:

_Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)_

Revise both the datatype of the grammar field in the experiment and the field in the "My grammar" storage.

**Comment by leichenxu** [comment]
the progrem was only in experiment section, the type was varchar, now is text
