### ISSUE TITLE
Cross-validation tick is not saved

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#141]
The cross-validation option should be stored in the experiment when saved or saved and run.

Besides, the label should be "Cross-validation run" instead of "Cross validation run".

**Comment by leichenxu** [comment]
@jmcolmenar tick is saved, 
![image](https://user-images.githubusercontent.com/46742711/85982372-007c8a80-b9e6-11ea-92a0-8afba74c899a.png)
