### ISSUE TITLE
Download results should be available for stopped runs

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#178]
![image](https://user-images.githubusercontent.com/4963260/104011384-4d6bc580-51ae-11eb-93a2-797d64642747.png)

**Comment by AndreoPSullivan** [comment]
The model it's needed for it to be downloaded but cannot be stored in each execution because of the lack of data sent in the Observers (it only contains MaxGenerations, CurrentGeneration, BestObjective) a that's part of the SimpleGenerticAlgorithm from jeco.

**Comment by jmcolmenar** [comment]
Yes, but the message given by the application is confusing because it says "wait until all runs have finished" and the question is that all runs have finished. In this situation the stats shoud be downloaded without model. Note that in case several runs were launched, maybe some of them could be stopped and some other not.

**Comment by AndreoPSullivan** [comment]
Fine, I'll take it into account.
