### ISSUE TITLE
Concurrent execution fails

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#194]
If two experiments are run at the same time, several exceptions occur and runs are corrupted.

Check concurrent execution.

**Comment by AndreoPSullivan** [comment]
I detected it was happening between GE+DE executions only and I think I found the reason why it wasn't working properly. 
![image](https://user-images.githubusercontent.com/25351207/106180761-08c7be80-619d-11eb-9529-fba47e25a35e.png)
It seems to work fine now.
