### ISSUE TITLE
Paralelismo RabbitMQ

### ISSUE THREAD

**Issue by rmartinsanta** [GRAFO-URJC/WebGE#225]
Utilizar RabbitMQ para encolar los runs al crear el experimento, el siguiente proyecto de ejemplo te puede ser muy util: https://spring.io/guides/gs/messaging-rabbitmq/

Realizar la tarea en dos fases:
1. Primero, utilizat RabbitMQ con la configuración por defecto, solo activando la opción de colas persistentes. De esta forma, si un mensaje es recibido pero no confirmado (ACK), al arrancar la aplicación se reinicia automáticamente la tarea correspondiente. Comprobar que la aplicación funciona de forma correcta comparando los resultados contra el otro executor.
2. Modificar la configuración de RabbitMQ para que los mensajes recibidos que no sean confirmados se considere NACK o Rejected (confirmación negativa), y en vez de reencolar estos mensajes, que sean movidos a otra cola (Dead Letter Exchanges).

Información sobre los tipos de confirmación en RabbitMQ https://www.rabbitmq.com/confirms.html
Dead Letter Exchange: https://www.rabbitmq.com/dlx.html

Cualquier problema o duda que te vaya surgiendo ve comentándolo.

**Comment by antoniocao99** [comment]
@rmartinsanta 

He empezado a plantear la implementación con rabbitMQ y tengo ciertas dudas de como organizar todo.

Supongo que la idea es: desde el service encolar los runs en rabbit, para que los consuma desde el mismo service (con el threadpool). Creo que esto no tiene sentido.

¿Debería crear otra clase que se encargue de ejecutar los runs?

Tambien entiendo que al terminar de ejecutar deberia mandar por otra cola el reporte al usuario.

¿Como lo ves?

**Comment by rmartinsanta** [comment]
Buenas tardes,
la solución correcta es la que planteas en segundo lugar. El servicio crea todos los runs, y los encola en Rabbit, y existen de 1 a N listeners que van recuperando y ejecutando las tareas de la cola. 
Los resultados de la ejecución se pueden enviar de vuelta a ese servicio o a otro a través de una nueva cola, o se puede meter directamente a la base de datos, depende de para que los necesite o vaya a usar la aplicación.

**Comment by antoniocao99** [comment]
@rmartinsanta 

Hola buenas.
He ido avanzando poco a poco, ya soy capaz de encolar los mensajes y consumirlos. Mis dudas son las siguientes.

La primera es que entiendo que toda comunicación entre el listener y el service debe realizarse a través de las colas de rabbit; es decir que nada de hacer variables static para acceder a ellas.

Otra es la siguente: entiendo que el listener y el service se ejecutan en paralelo internamente. Por ello supongo que deberia añadir una ED concurrente tipo una barrera, semaforo para esperar desde el service a que termine el listener de ejecutar los runs.
¿Suena bien o me estoy complicando mas de lo necesario?

PD. En el comment anterior dijiste que existen de 1 a N listeners. Yo entiendo que solo existe un listener que mete al threadpool (que esta declarado en la misma clase que el metodo que actua de listener) los runs que consume.

Saludos.

**Comment by rmartinsanta** [comment]
Buenas tardes, te comento por puntos:

> La primera es que entiendo que toda comunicación entre el listener y el service debe realizarse a través de las colas de rabbit; es decir que nada de hacer variables static para acceder a ellas.

Correcto, toda comunicación debería realizarse a través de las colas de RabbitMQ. Para ello vas a necesitar dos colas, una para los runs o unidades de trabajo, y otra para los resultados. Esto da a pié a que en el futuro se pueda partir la aplicación en microservicios, donde los workers que ejecutan el trabajo no tienen ni idea de como funciona el core de la aplicación y viceversa.

> Otra es la siguente: entiendo que el listener y el service se ejecutan en paralelo internamente. Por ello supongo que deberia añadir una ED concurrente tipo una barrera, semaforo para esperar desde el service a que termine el listener de ejecutar los runs.
¿Suena bien o me estoy complicando mas de lo necesario?

Spring crea uno o varios hilos para los listeners, por lo que se están ejecutando en paralelo, sí. ¿Para qué necesitarías que el servicio esté esperando a los resultados con una barrera o similares? Podría ser suficiente con tener un listener que recibe los resultados de los experimentos y los va guardando a la base de datos o la operación que tenga que hacer para cada uno. Si hay que hacer alguna operación especial cuando están todos los de un experimento, puede ejecutar esa comprobación cada vez que llegue un resultado para comprobar si el experimento ha terminado. En general, cuantas menos estructuras de datos concurrentes se usen mejor, aumentan bastante la complejidad. De esta forma, además, liberamos el hilo que en caso contrario estaría esperando a que termine el experimento.

> En el comment anterior dijiste que existen de 1 a N listeners. Yo entiendo que solo existe un listener que mete al threadpool (que esta declarado en la misma clase que el metodo que actua de listener) los runs que consume.

El listener no debería crear ningún Thread, ni usar un Executor. Debería ejecutar el run o el trabajo que le toca en el hilo actual. Para escalar la aplicación, se puede aumentar el número de listeners, sin modificar el código, de forma dinámica, es un parámetro de configuración de Spring: https://docs.spring.io/spring-amqp/docs/current/reference/html/#listener-concurrency
Además, hacerlo así además debería simplificar bastante el listener.

Cualquier comentario no te cortes, puede que haya entendido mal cualquier cosa.
Saludos.

**Comment by antoniocao99** [comment]
@rmartinsanta 

Buenas! Te comento como voy.

Ya podemos encolar, consumir y medio ejecutar los runs utilizando rabbitmq.
Digo medio por las siguientes cosas:

- 	 Con la configuracion por defecto, si en un run salta una excepcion, este run vuelve a re-encolarse. Esto es bastante inconveniente para nosotros pues nuestros runs suelen terminar cuando salta algun tipo de excepcion interna de ellos. Para salir del paso de momento he añadido una propiedad al application.properties que evita este re-encolamiento. Mencionar que con dicha propiedad, los runs no se muestran como "unacked" en el dashboard de rabbit.

- 	 Lo siguiente a mencionar es que el codigo que gestiona los runs esta fuertemente acoplado: Tanto en la version legacy como en la de threadpool, requerimos de EDs para almacenar los runs y recuperarlos cuando consideremos. Si aqui movemos los runs a otra clase, no podremos utilizar estas EDs y por tanto, adios a borrar runs, detener runs...

- 	Algo que tampoco parece funcionar de momento es el cambiar el estado del run cuando este falla y salta la excepcion.  El frontend no parece enterarse, pues su estado no cambia. En el logger si se muestra el stacktrace (al igual que antes). Quizas esto se deba a lo mencionado en el punto anterior?

Un saludo.

**Comment by rmartinsanta** [comment]
Buenos días, te voy contando por puntos. Todavía no he mirado el código así que puede que algunos puntos no tengan mucho sentido, esta tarde te digo en más detalle.

> Con la configuracion por defecto, si en un run salta una excepcion, este run vuelve a re-encolarse. Esto es bastante inconveniente para nosotros pues nuestros runs suelen terminar cuando salta algun tipo de excepcion interna de ellos. Para salir del paso de momento he añadido una propiedad al application.properties que evita este re-encolamiento. Mencionar que con dicha propiedad, los runs no se muestran como "unacked" en el dashboard de rabbit.

Personalmente pondría el código del listener bajo un try catch, y decidimos según el tipo de excepción.
```java
try {
    this.doWork(message);
} catch ([Excepciones que signifiquen que el experimento ha acabado]){
    log.info("Run XYZ finished [...]")
    this.sendResult(result);
} catch ([Excepciones fatales, no podemos recuperarnos] t){
    // Escalamos especificando que el mensaje no se reencole, porque NO es un error transitorio. Si existe un DLX/DLQ, RabbitMQ lo deberia meter ahi para poder analizarlo luego comodamente.
    log.error("Unrecoverable error un WebGE worker, see DLQ for more information: " + t)
    throw new AmqpRejectAndDontRequeueException("Not recoverable exception in WebGE Runner, ", t);
} catch ([Fallos transitorios, si reintentamos podria funcionar] t){
    log.warning("Recoverable error un WebGE worker, retrying: " + t)
    throw t; // Por defecto, en caso de la mayoria de excepciones el mensaje se reencola, que es el comportamiento que has observado.
}

```

> Lo siguiente a mencionar es que el codigo que gestiona los runs esta fuertemente acoplado: Tanto en la version legacy como en la de threadpool, requerimos de EDs para almacenar los runs y recuperarlos cuando consideremos. Si aqui movemos los runs a otra clase, no podremos utilizar estas EDs y por tanto, adios a borrar runs, detener runs...

Lo reviso.

> Algo que tampoco parece funcionar de momento es el cambiar el estado del run cuando este falla y salta la excepcion. El frontend no parece enterarse, pues su estado no cambia. En el logger si se muestra el stacktrace (al igual que antes). Quizas esto se deba a lo mencionado en el punto anterior?

Lo reviso también.

**Comment by rmartinsanta** [comment]
@antoniocao99 Si puedes crea la PR y mencióname, para poder ir revisando y probando. Si añades commits a la rama se ponen automáticamente en la PR.

**Comment by rmartinsanta** [comment]
Te comento el tercer punto en la Pull Request, para que puedas seguir avanzando con ello
