### ISSUE TITLE
Runs fail at the end of execution

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#232]
After a run finishes, the run fails, and the log shows the following error:

webge-gramev-1    | 2022-06-21 10:39:32.721  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : Run #0
webge-gramev-1    | 2022-06-21 10:39:32.722  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : ========
webge-gramev-1    | 2022-06-21 10:39:32.722  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : Execution time: 59.623 seconds.
webge-gramev-1    | 2022-06-21 10:39:32.725  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : @@;X3*X4+X8*X3*X4
webge-gramev-1    | 2022-06-21 10:39:32.726  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : Execution report
webge-gramev-1    | 2022-06-21 10:39:32.726  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : ==================
webge-gramev-1    | 2022-06-21 10:39:32.726  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : #Run;Obj.;Model;Time
webge-gramev-1    | 2022-06-21 10:39:32.727  INFO 1 --- [ntContainer#1-1] c.engine.algorithm.SymbolicRegressionGE  : 1;0.575166482215847;X3*X4+X8*X3*X4;59.623
webge-gramev-1    | 2022-06-21 10:39:32.750  WARN 1 --- [ntContainer#0-1] c.g.w.s.listener.ReportsListenerService  : Uncaught exception: java.lang.Exception: Cannot invoke "com.gramevapp.web.repository.RunRepository.findById(Object)" because "this.runRepository" is null

**Comment by antoniocao99** [comment]
@jmcolmenar @rmartinsanta 

He llegado a la raiz del problema pero no entiendo por que sucede.

El problema es que se crean diferentes instancias del RunService.
Cosa que no deberia pasar pues por defecto todos los Service son singleton.

Al menos, haciendo un System.out.println(this) (dentro de un metodo de RunService) salen varias direcciones de memoria diferentes.

En concreto, hay una direccion que corresponde al service "original", el cual **nunca** tira la excepcion NullPointer.

Y por el otro lado salen direcciones de memoria diferentes que supongo que corresponde a estos Service que no deberian volver a crearse. 
Son estas instacias los que tiran la excepcion, ya que por algun motivo inizializan el campo runRepository a null.

Para terminar, esto no sucede con la implementación basada en Threadpool. ¿Será algo de Rabbit?

Saludos

**Comment by rmartinsanta** [comment]
Elimina los Autowired y pásalos por el constructor para encontrar quién esta creando el objeto mal sin las dependencias:

Regulero
```java
    @Autowired
    RunRepository runRepository;

    @Autowired
    ExperimentRepository experimentRepository;
```

Mejor:
```java
    final RunRepository runRepository;

    final ExperimentRepository experimentRepository;

    public RunService(ExperimentRepository experimentRepository, RunRepository runRepository) {
        this.experimentRepository = experimentRepository;
        this.runRepository = runRepository;
    }
```

**Comment by antoniocao99** [comment]
Buenas, he sacado la siguiente conclusion:
El reporte final de los runs esta dividido en muchos sitios. 
- En algunos casos se lanza en el propio algoritmo. 
- En otros lo tratamos cuando salta la excepcion en el listener.

El problema: los propios runs tienen (y necesitan) acceso a los services. 
Cada run tiene acceso a un objeto del runService, entre otros.
En esta nueva implementación es necesario serializar y deserializar dichos runs (junto a todos sus atributos). 
En estos services al deserializar, se llama a sus constructores (los cuales solo deberia llamar Spring). 
Sin embargo, algunos atributos del run de inicializan correctamente; otros no, como es el caso de runService, en concreto el atributo del runRepository. 

La unica alternativa que se me ocurre seria crear algunos services como static (en cualquier clase ajena a listeners etc), y utilizar esos, pudiendo eliminarlos de cada Run.
Esto evidentemente, rompe con la arquitectura de microservicios.

@rmartinsanta

**Comment by rmartinsanta** [comment]
Creo que la mejor solución, aunque seguramente sea la más compleja, es dividir las responsabilidades de los actuales run en dos clases diferentes:
1. DTO / POJO / Clase "tonta": los datos que necesita para ejecutar, sin la propia lógica. 
2. La clase con los propios métodos, que pasaría a ser un servicio o equivalente, y necesita objetos de la clase anterior que son los que tiene los datos para poder ejecutar sus métodos.

De esta forma, podemos serializar/deserializar la primera sin problemas en cualquier sitio, ¿cómo lo ves?

**Comment by antoniocao99** [comment]
Parece funcionar. Codigo pusheado.

Sin embargo siguen aparenciendo errores, pero se ha arreglado el problema anterior.
Sigo trabajando en estos nuevos errores.

**Comment by rmartinsanta** [comment]
El error reportado originalmente arreglado en #233
