### ISSUE TITLE
Availability of "Download grammar" button

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#6]
Button to "Download grammar" (configExperiment page) shouldn't be activated because if there is nothing and it is pressed it will download txt with nothing

**Comment by leichenxu** [comment]
The button "download grammar" is in grammarRepository page, and works well, maybe this issue is refered to "Download Data type file" button in issue #5. In configexperiment page, button "Download grammar" not exist.
