### ISSUE TITLE
Delete experiment

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#78]
Button to delete experiment in "My experiments" is not working. Remember to ask for confirmation.

**Comment by leichenxu** [comment]
i will check it

**Comment by jmcolmenar** [comment]
Test data cannot be modified (saved) after runs are made.

**Comment by jmcolmenar** [comment]
Can the "refresh for load" message be modified? I mean, can be automatically refreshed?

**Comment by leichenxu** [comment]
> Can the "refresh for load" message be modified? I mean, can be automatically refreshed?

yes, no problem

**Comment by leichenxu** [comment]
> Test data cannot be modified (saved) after runs are made.

to ensure, that mean after i made runs i cannot change in test dataset or you can't save it after run it?

**Comment by leichenxu** [comment]
> Button to delete experiment in "My experiments" is not working. Remember to ask for confirmation.

i cannot recreate the problems with this issue
![image](https://user-images.githubusercontent.com/46742711/83980261-84c27d00-a914-11ea-8c27-2a6df45fa097.png)
![image](https://user-images.githubusercontent.com/46742711/83980262-868c4080-a914-11ea-9302-710ec3dc695e.png)
![image](https://user-images.githubusercontent.com/46742711/83980263-87bd6d80-a914-11ea-916f-1dc7f6ece05a.png)

**Comment by leichenxu** [comment]
related  #83
